server_ipv4: 127.0.0.1
server_port: 8080
access_log_path: './logs/access.log'
error_log_path: './logs/error.log'
methods:
    - HEAD
    - GET
    - OPTIONS
    - POST
    - PUT
    - DELETE
server_name: localhost
webroot: './example_site'
custom_error_pages: false
default_indexes:
    - index.html
    - index.htm
    - index.txt
error_pages:
    403: docs/403.html
    404: docs/404.html
    405: docs/405.html
    500: docs/500.html
    501: docs/500.html
listen_mode: false
file_ext:
    - html
    - htm
    - png
    - txt
    - jpeg
    - jpg
    - gif
    - css
